name: 'Hetzner Deployer'
description: 'Rolling deployments using Hetzner Loadbalancers for zero downtime deployments'
author: Carlos Florêncio

inputs:
  servers:
    description: 'List of server ips (CSV)'
    required: true
  commands:
    description: 'Commands to run on each server (List)'
    required: true
  hetzer_token:
    description: 'Hetzner API token with write permissions (string)'
    required: true
  ssh_user:
    description: 'SSH user (string)'
    required: true
    default: root
  ssh_port:
    description: 'SSH port (string)'
    required: true
    default: "22"
  ssh_key:
    description: 'SSH private key file (string)'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'server'
  color: 'red'
